### ISSUE TITLE
consistency in mathematical proofs for eg current multiple trials works if all corssings are of the same size but if that is not the case, statistically atleast i cannot say that it is a random series of trials.  mentioned under verified core verified core

### ISSUE THREAD

**Issue by ahsanbutt95** [sweetpea-org/sweetpea-py#24]

**Comment by mflatt** [comment]
Assuming I understand the issues, this has been covered by changes related to the `MinimumTrials` constraint. When you have a mutliple-crossings design, then when the crossings imply different numbers of trials, it's the same as having a `MiniumumTrials` constraint for the larger of the two sizes. A non-multiple of the crossing size is generated as sampling a prefix of a multiple of the crossing size. For uniform combinatoric sampling, in particular, counting distinct prefixes is different than counting the distinct solutions rounded up to a multiple of the crossing size. For SAT-based encodings, counting constraints for the extra trials are expressed as "less or equal" instead of "equal" to get this part right.
