### ISSUE TITLE
Need way of defining a level for a regular factor

### ISSUE THREAD

**Issue by musslick** [sweetpea-org/sweetpea-py#40]
When defining a constraint, e.g.

`exclusion_constraint = exclude(my_factor, my_level)`

the constraint expects a factor and a level. However, for regular factors, there is no way of declaring a level outside the declaration of a factor. What we need is a way of defining levels of regular factors, e.g.

`my_level = simple_level('yes')`

**Comment by pdarragh** [comment]
I think instead of allowing for freestanding simple levels separate from their factors, it might be better to tell the constraint how to identify the level within the given factor, either by name or some sort of index:

```python
def exclude(factor: Factor, level: Union[Level, str]):
    if isinstance(level, str):
        level = factor.get_level(level)
    ...

exclusion_constraint = exclude(my_factor, 'my_level')
```

Alternatively, the level could be retrieved from the factor before being passed in:

```python
def exclude(factor: Factor, level: Level):
    ...

exclusion_constraint = exclude(my_factor, my_factor.get_level('my_level'))
```

This prevents the user from accidentally confusing levels from different factors with similar names, like in the Stroop experiments how you could easily end up with two distinct `red` levels that belong to different factors. In general, I think we should prefer a design where levels are closely coupled with factors but are readily accessible or indexable for all the externally usable functionality.

Does this seem like a reasonable enough solution to your problem, @musslick? Or do you think there is other benefit to be gained from providing access to levels external to their factors?

**Comment by musslick** [comment]
Thank you for this super quick response. I absolutely agree—both solutions you are suggesting sound great. Specifying the level as a string (first solution) seems less cumbersome, so maybe this is the best solution?

**Comment by ahsanbutt95** [comment]
There was something similar implemented in the tests but I realize it aided only as a test utility. I am also in favor of the first suggestion Pierce made. I can make these and the other changes. If someone gets to them before I do assign the issue to yourself on Git.(@pdarragh )

**Comment by pdarragh** [comment]
I'm already in the middle of refactoring some stuff with levels and factors, so @ahsanbutt95 I'll take this as per our team discussion 2021-05-05.
